version: '3.3'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysql_my_django_app
    ports:
      - '3306:3306'
    environment:
      MYSQL_DB: 'django_app_demo'
      MYSQL_PASSWORD: 'password'
      MYSQL_USER: 'root'

